Task4394.dev Was changed twig mini-pager(added arrows) reworks block "Fashion"- changes display mode
Dexs1/M_project pull request #13
Opened 2022-02-17 13:10 UTC by Dexs1

https://redmine.devbranch.work/issues/4394

2022-02-17 13:14 UTC, Dexs1 commented
And also added some styles to blocks that were themed earlier for correct rendering.

2022-02-18 06:50 UTC, devbranch-vitaliy requested changes

2022-02-18 06:50 UTC, devbranch-vitaliy commented on web/themes/custom/kitrab/src/scss/_grouprecent.scss
> +  //}
Dead code
```suggestion
```

2022-02-18 06:50 UTC, devbranch-vitaliy commented on web/themes/custom/kitrab/src/scss/_life-news.scss
> +}
Need a blank space at the end of the file.
```suggestion
}

```

2022-02-18 06:50 UTC, devbranch-vitaliy commented on web/themes/custom/kitrab/src/scss/_mainpage.scss
> +}
Need a blank space at the end of the file.
```suggestion
}

```

2022-02-18 06:50 UTC, devbranch-vitaliy commented on web/themes/custom/kitrab/src/scss/app.scss
> +
At the end of the file should be only 1 blank space.
```suggestion
```

2022-02-18 07:54 UTC, devbranch-vitaliy approved these changes

2022-02-18 07:54 UTC, merged